version: '3.5'

services:
    backend:
        build: 
            context: ../
            dockerfile: docker/Dockerfile
        image: ${WEBAPP_IMAGE_NAME}
        volumes:
            -  log_data:/app/log
        environment:
            - "TZ=Europe/Budapest"
            - "OPENAI_API_KEY=${OPENAI_API_KEY}"
            - "LOG_DIR=${LOG_DIR}"
            - "LOGURU_DIAGNOSE=${LOGURU_DIAGNOSE}"
            - "LOGURU_FORMAT=${LOGURU_FORMAT}"
        ports:
            - 80:80

volumes:
    log_data:
