These are the fields of issues table:
    id serial4 NOT NULL,
    tracker_id int4 NOT NULL,
    project_id int4 NOT NULL,
    subject varchar DEFAULT ''::character varying NOT NULL,
    description text NULL,
    due_date date NULL,
    category_id int4 NULL,
    status_id int4 NOT NULL,
    assigned_to_id int4 NULL,
    priority_id int4 NOT NULL,
    fixed_version_id int4 NULL,
    author_id int4 NOT NULL,
    lock_version int4 DEFAULT 0 NOT NULL,
    created_on string NULL, # time of creation as string
    updated_on string NULL, # time of update as string
    start_date date NULL,
    done_ratio int4 DEFAULT 0 NOT NULL,
    estimated_hours float8 NULL,
    parent_id int4 NULL,
    root_id int4 NULL,
    lft int4 NULL,
    rgt int4 NULL,
    is_private bool DEFAULT false NOT NULL,
    closed_on timestamp NULL,
    CONSTRAINT issues_pkey PRIMARY KEY (id)