These are the fields of projects table:
    id serial4 NOT NULL,
    "name" varchar DEFAULT ''::character varying NOT NULL,
    description text NULL,
    homepage varchar DEFAULT ''::character varying NULL,
    is_public bool DEFAULT true NOT NULL,
    parent_id int4 NULL,
    created_on timestamp NULL,
    updated_on timestamp NULL,
    identifier varchar NULL,
    status int4 DEFAULT 1 NOT NULL,
    lft int4 NULL,
    rgt int4 NULL,
    inherit_members bool DEFAULT false NOT NULL,
    default_version_id int4 NULL,
    default_assigned_to_id int4 NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id)