These are the fields of users table:
    id serial4 NOT NULL,
    login varchar DEFAULT ''::character varying NOT NULL,
    hashed_password varchar(40) DEFAULT ''::character varying NOT NULL,
    firstname varchar(30) DEFAULT ''::character varying NOT NULL,
    lastname varchar(255) DEFAULT ''::character varying NOT NULL,
    "admin" bool DEFAULT false NOT NULL,
    status int4 DEFAULT 1 NOT NULL,
    last_login_on timestamp NULL,
    "language" varchar(5) DEFAULT ''::character varying NULL,
    auth_source_id int4 NULL,
    created_on timestamp NULL,
    updated_on timestamp NULL,
    "type" varchar NULL,
    identity_url varchar NULL,
    mail_notification varchar DEFAULT ''::character varying NOT NULL,
    salt varchar(64) NULL,
    must_change_passwd bool DEFAULT false NOT NULL,
    passwd_changed_on timestamp NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)